output "service_principal_password" {
  value       = azuread_service_principal_password.pw.value
  sensitive   = true
  description = "The client_secret for the service principal"
}

output "service_principal" {
  value       = azuread_service_principal.sp
  description = "The service principal generated by this module."
  sensitive   = true
}

output "application" {
  value       = azuread_application.app
  description = "The Azure AD application generated by this module."
  sensitive   = true
}

